Repository mash-up-kr/DoriDori_iOS, pull requests merged in 2022-08, with the labels that each got.

#39 Feature/speech bubble
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Common/Extensions/UIView+Extension.swift
  DoriDori_iOS/DoriDori_iOS/Common/KeywordView/KeywordView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ItemType/HomeSpeechBubbleItemType.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ItemType/MyPageMySpeechBubbleViewItemType.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ItemType/MyPageOtherSpeechBubbleItemType.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/MySpeechBubbleView/HomeMySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/MySpeechBubbleView/HomeMySpeechBubbleViewCell.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/MySpeechBubbleView/MyPageMySpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/MySpeechBubbleView/MyPageMySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/MySpeechBubbleView/MySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/OtherSpeechBubbleView/HomeOtherSpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/OtherSpeechBubbleView/HomeOtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/OtherSpeechBubbleView/MyPageOtherSpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/OtherSpeechBubbleView/MyPageOtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/OtherSpeechBubbleView/OtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ViewType/CommentableSpeechBubbleViewType.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ViewType/SpeechBubbleViewLikeable.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ViewType/SpeechBubbleViewTaggable.swift
  DoriDori_iOS/DoriDori_iOS/Common/SpeechBubble/ViewType/SpeechBubbleViewType.swift
  DoriDori_iOS/DoriDori_iOS/Resources/Assets.xcassets/right_bracket.imageset/Contents.json
  DoriDori_iOS/DoriDori_iOS/Resources/Assets.xcassets/right_bracket.imageset/right_bracket.pdf
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/AnswerComplete/AnswerCompleteViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageCell/OtherQuestionCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageHeaderView/MyPageHeaderView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageViewController.swift
Labels: 🙏 review request

#47 Imp/git ignore
  .gitignore
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.xcworkspace/xcuserdata/user.xcuserdatad/UserInterfaceState.xcuserstate
  DoriDori_iOS/DoriDori_iOS.xcodeproj/xcuserdata/user.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🙏 review request

#45 Feature/profile keyword
  .DS_Store
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Scene/Profile/Profile.storyboard
  DoriDori_iOS/DoriDori_iOS/Scene/Profile/Profile/KeywordView/ProfileKeywordView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Profile/Profile/KeywordView/ProfileKeywordView.xib
  DoriDori_iOS/DoriDori_iOS/Scene/Profile/Profile/ProfileKeywordViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Profile/Profile/ProfileUploadViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Sign/EmailSignIn/EmailSignInViewController.swift
Labels: 🙏 review request, 🧚‍♂️ 지인 🧚‍♂️

#48 Feature/my page
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/AppStart/AppCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Common/APIs/UserInfoRequest.swift
  DoriDori_iOS/DoriDori_iOS/Common/Coordinator/Coordinator.swift
  DoriDori_iOS/DoriDori_iOS/Common/Extensions/Array+Extension.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/ErrorModel.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Network.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Requestable.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/ResponseModel.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/KeywordView/KeywordView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/LevelView/LevelView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ItemType/HomeSpeechBubbleItemType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ItemType/MyPageMySpeechBubbleViewItemType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ItemType/MyPageOtherSpeechBubbleItemType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/MySpeechBubbleView/HomeMySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/MySpeechBubbleView/HomeMySpeechBubbleViewCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/MySpeechBubbleView/MyPageMySpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/MySpeechBubbleView/MyPageMySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/MySpeechBubbleView/MySpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/OtherSpeechBubbleView/HomeOtherSpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/OtherSpeechBubbleView/HomeOtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/OtherSpeechBubbleView/MyPageOtherSpeechBubbleCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/OtherSpeechBubbleView/MyPageOtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/OtherSpeechBubbleView/OtherSpeechBubbleView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ViewType/CommentableSpeechBubbleViewType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ViewType/SpeechBubbleViewLikeable.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ViewType/SpeechBubbleViewTaggable.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/SpeechBubble/ViewType/SpeechBubbleViewType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/AnswerComplete/AnswerCompleteViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/Model/UserInfoModel.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageCell/MyQuestionCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageCell/OtherQuestionCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageHeaderView/MyPageCollectionViewCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageProfileView/MyPageProfileView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageReactor.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageRepository.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageTab.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageTabCollectionViewCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageViewModel.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/QuestionReceived/QuestionReceivedViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/SeeAll/SeeAllViewController.swift
Labels: 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request

#51 Feature/setting
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/AppStart/AppCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Common/Coordinator/Coordinator.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Network.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageProfileView/MyPageProfileView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageReactor.swift
  DoriDori_iOS/DoriDori_iOS/Scene/MyPage/MyPageViewController.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/DoriDoriSettingItem.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingCollectionViewCell.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingCollectionViewHeaderView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingReactor.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingSectionModel.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Setting/SettingViewController.swift
Labels: 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request

#59 Feature/scheme
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/AppStart/SceneDelegate.swift
  DoriDori_iOS/DoriDori_iOS/Common/Extensions/UIViewController+Extension.swift
  DoriDori_iOS/DoriDori_iOS/Info.plist
  DoriDori_iOS/DoriDori_iOS/Scheme/Scheme.swift
  DoriDori_iOS/DoriDori_iOS/Scheme/SchemeExecuter.swift
  DoriDori_iOS/DoriDori_iOS/Scheme/SchemeParser.swift
  DoriDori_iOS/DoriDori_iOS/Scheme/URLContant.swift
Labels: 🔥민호🔥

#73 activityIndicator
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Scene/Common/ActivityIndicator/DoriDoriActivityIndicator.swift
Labels: ✨ feature, 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request

#76 ✨ [#75] 리프레시하는 로직 추가
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Common/APIs/RefreshTokenRequest.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Authentication/AuthenticationRepository.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Authentication/RefreshModel.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/DoriDoriError.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Network.swift
  DoriDori_iOS/DoriDori_iOS/Common/Network/Requestable.swift
  DoriDori_iOS/DoriDori_iOS/Common/UserDefault/UserDefault+Value.swift
Labels: ✨ feature, 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request

#56 ✨ toast view UI
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Scene/Common/DoriDoriToastView.swift
Labels: 😶‍🌫️ 서영 😶‍🌫️

#68 Feature/question
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DoriDori_iOS/DoriDori_iOS/Common/APIs/MyWardListRequest.swift
  DoriDori_iOS/DoriDori_iOS/Common/APIs/QuestionAtCommunityRequest.swift
  DoriDori_iOS/DoriDori_iOS/Common/APIs/QuestionToUserRequest.swift
  DoriDori_iOS/DoriDori_iOS/Common/Coordinator/Coordinator.swift
  DoriDori_iOS/DoriDori_iOS/Common/LocationManager/CLLocationManger+Rx.swift
  DoriDori_iOS/DoriDori_iOS/Common/LocationManager/DoriDoriLocationError.swift
  DoriDori_iOS/DoriDori_iOS/Common/LocationManager/DoriDoriLocationManager.swift
  DoriDori_iOS/DoriDori_iOS/Common/LocationManager/LocationManager.swift
  DoriDori_iOS/DoriDori_iOS/Info.plist
  DoriDori_iOS/DoriDori_iOS/Scene/Common/DropDownView.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/DropDownItem/AnonymousDropDownItem.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/DropDownItem/MyWardDropDownItem.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/Model/MyWardModel.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/QuestionCoordinator.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/QuestionReactor.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/QuestionRepository.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/QuestionType.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Question/QuestionViewController.swift
Labels: ✨ feature, 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request

#74 alertViewController
  DoriDori_iOS/DoriDori_iOS.xcodeproj/project.pbxproj
  DoriDori_iOS/DoriDori_iOS/Scene/Common/Alert/AlertAction.swift
  DoriDori_iOS/DoriDori_iOS/Scene/Common/Alert/AlertViewController.swift
Labels: 😶‍🌫️ 서영 😶‍🌫️, 🙏 review request
